#Deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
spec:
  selector:
    matchLabels:
      name: dotnet-app
  template:
    metadata:
      labels:
        name: dotnet-app
    spec:
      containers:
      - name: dotnet-app
        image: thakur08/azure-devops
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
---
#service.yml
apiVersion: v1
kind: Service
metadata:
  name: dotnet-app
spec:
  type: LoadBalancer
  selector:
    name: dotnet-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
